server:
  port: 8761
#配置zipKin Server的地址
#spring.zipkin.base-url=http://localhost:8005
spring:
  output:
    ansi:
      enabled: always
  application:
    name: eureka

info:
  version: "0.1.0"


logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file: eureka.log