
server:
  port: 8200
  servlet:
      context-path: /uaa
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
          prefer-ip-address: true
spring:
  application:
    name: oauth
info:
  version: "0.1.0"
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file: oauth.log
hystrix:
  shareSecurityContext: true

ribbon:
  eager-load:
    enabled: true
    clients: feign


  #pattern:
    #file: "%d{yyyy/MM/dd } - %msg%n"





