server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://beta.buchuju.net:8761/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: moment
        uri: lb://moment
        predicates:
        - Path=/moment/**
      - id: moments
        uri: lb://moment
        predicates:
        - Path=/moments/**
      #category
      - id: moment
        uri: lb://moment
        predicates:
        - Path=/category/**
      - id: moments
        uri: lb://moment
        predicates:
        - Path=/categories/**
      #message
      - id: message
        uri: lb://message
        predicates:
        - Path=/message/**
      - id: messages
        uri: lb://message
        predicates:
        - Path=/messages/**
      #mark
      - id: mark
        uri: lb://mark
        predicates:
        - Path=/mark/**
      - id: marks
        uri: lb://mark
        predicates:
        - Path=/marks/**
      #comment
      - id: comment
        uri: lb://comment
        predicates:
        - Path=/comment/**
      - id: comments
        uri: lb://comment
        predicates:
        - Path=/comments/**
      #accusation
      - id: accusation
        uri: lb://accusation
        predicates:
        - Path=/accusation/**
      - id: accusations
        uri: lb://accusation
        predicates:
        - Path=/accusations/**

info:
  version: "0.1.0"
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file: gateway.log


  #pattern:
    #file: "%d{yyyy/MM/dd } - %msg%n"





